#!/bin/sh

if [ ! -f "$HOME/.config/nvim/init.vim" ]; then
    cd $HOME/.config/nvim

    # Create the temp dir
    mkdir -p $HOME/.local/share/nvim/tmp/backup \
    $HOME/.local/share/nvim/tmp/undo \
    $HOME/.local/share/nvim/tmp/swap \
    $HOME/.local/share/nvim/tmp/view
    echo "DONE: Create tmp directory on ~/.local/share/nvim"

    if command -v nvim &> /dev/null; then
        nvim -c ':PlugInstall' -cqa
    else
        "You don't have Neovim on your path."
        exit
    fi

    echo "DONE: All plugin installed"
else
    echo "You have run this script!"
fi
